CREATE DATABASE user_management;

USE user_management;

CREATE TABLE IF NOT EXISTS users (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(100) NOT NULL UNIQUE,
                                     password VARCHAR(255) NOT NULL,
                                     email VARCHAR(100) NOT NULL UNIQUE
);

-- ###################################################################################################################

-- Insert
MERGE INTO users (id, username, password, email) KEY(id) VALUES (1,'Berru','123456','berruhanedar@gmail.com' )

-- Select
select * FROM users;

-- Find User
SELECT  *  FROM users WHERE username="Berru" AND "123456";

-- Update
UPDATE users SET username="Berru", password="12345644", email="berruhanedar@gmail.com" WHERE id=1;

-- delete
DELETE FROM users  WHERE id=1;
